version: "3.8"

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Bhuvi@2005
      MYSQL_DATABASE: employee_management
    ports:
      - "3308:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    environment:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

  
volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
